# Artificial Neural Network

Data table display for Pandas dataframes can be enabled by running:
```python
from google.colab import data_table
data_table.enable_dataframe_formatter()
```

### Importing the libraries

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

np.set_printoptions(suppress=True)

In [36]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data Science/Deep Learning/MLP/Churn_Modelling.csv')
dataset.iloc[:, 3:-1]

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [39]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

**Separating features from target**

In [69]:
X = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1]

In [41]:
print(X)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

In [42]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64


### Encoding categorical data

Label Encoding the "Gender" column

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#X[:, 2] = le.fit_transform(X[:, 2])
X.loc[:, 'Gender'] = le.fit_transform(X.loc[:, 'Gender'])

<ipython-input-43-e136cf14375e>:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.loc[:, 'Gender'] = le.fit_transform(X.loc[:, 'Gender'])


In [61]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [44]:
print(X)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0           

One Hot Encoding the "Geography" column

**Note**: that ColumnTransformer.fit_transfrom() returns an array 

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)

In [74]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

**Note**: Feature Scaling is absolutely compulsory for Deep Learning, so we always scale!

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

Sequential Layer

In [49]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

**Note**: More commonly, for the activation function we'll use:

*   Rectifier function for the hidden layer
*   Sigmoid function for the output layer



In [50]:
# units should be tested serveral times to improve the accuracy
# rectifier = relu 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [51]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

The Activation Function "sigmoid" is for binary classification.
For multiclass, use "softmax".

In [52]:
# units = 1 output
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

Understanding the parameters:

*   optimizer: updates the weights for better accuracy
*   loss: the loss function
  * binary_crossentropy: Binary classification:
  * categorical_crossentropy: Multiclass classification

In [53]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

## Part 4 - Making the predictions and evaluating the model

**TODO**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

### Predicting the result of a single observation

**Note:** Dummies are at the beginning of the array. We are going to create a dataframe to better understand the processed features structure.

In [84]:
# Checking dummy variables position
X[0]

array([1.0, 0.0, 0.0, 619, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [79]:
dfX = pd.DataFrame(X, columns=['Country.isFrance', 'Country.isSpain', 'Country.isGermany', 'CreditScore', 'Gender',	'Age',	'Tenure',	'Balance',	'NumOfProducts',	'HasCrCard',	'IsActiveMember',	'EstimatedSalary'])
dfy = pd.DataFrame(y)

df = pd.concat([dfX, dfy], axis=1)
df

Country.isFrance Country.isSpain Country.isGermany CreditScore  Gender  \
0                 1.0             0.0               0.0         619  Female   
1                 0.0             0.0               1.0         608  Female   
2                 1.0             0.0               0.0         502  Female   
3                 1.0             0.0               0.0         699  Female   
4                 0.0             0.0               1.0         850  Female   
...               ...             ...               ...         ...     ...   
9995              1.0             0.0               0.0         771    Male   
9996              1.0             0.0               0.0         516    Male   
9997              1.0             0.0               0.0         709  Female   
9998              0.0             1.0               0.0         772    Male   
9999              1.0             0.0               0.0         792  Female   

     Age Tenure    Balance NumOfProducts HasCrCard IsActiveMember  \
0     42      2        0.0             1         1              1   
1     41      1   83807.86             1         0              1   
2     42      8   159660.8             3         1              0   
3     39      1        0.0             2         0              0   
4     43      2  125510.82             1         1              1   
...   ..    ...        ...           ...       ...            ...   
9995  39      5        0.0             2         1              0   
9996  35     10   57369.61             1         1              1   
9997  36      7        0.0             1         0              1   
9998  42      3   75075.31             2         1              0   
9999  28      4  130142.79             1         1              0   

     EstimatedSalary  Exited  
0          101348.88       1  
1          112542.58       0  
2          113931.57       1  
3           93826.63       0  
4            79084.1       0  
...              ...     ...  
9995        96270.64       0  
9996       101699.77       0  
9997        42085.58       1  
9998        92888.52       1  
9999        38190.78       0  

[10000 rows x 13 columns]

In [80]:
# Since we scaled the training set when training the algorithm, 
# we also have to scale the new test data
customer = [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]
customer_scaled = sc.transform(customer)
y_pred = ann.predict(customer_scaled)

1/1 [==============================] - 0s 143ms/step


In [81]:
print(y_pred)

[[0.02453582]]


**Solution**

There is only 5% chances the customer will leave to bank.

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [82]:
print(y_pred.reshape(1, -1))

[[0.02453582]]


In [83]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

y_test_array = y_test.values

# reshaping on n rows - 1 column
y_pred_reshaped = y_pred.reshape(len(y_pred), 1)
y_test_reshaped = y_test_array.reshape(len(y_test),1)
y_pred_test = np.concatenate((y_pred_reshaped, y_test_reshaped), 1)
print(y_pred_test)

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [85]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1519   76]
 [ 204  201]]


0.86